/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IllustrationLazyImport = createFileRoute('/illustration')()
const AboutMeLazyImport = createFileRoute('/aboutMe')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IllustrationLazyRoute = IllustrationLazyImport.update({
  id: '/illustration',
  path: '/illustration',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/illustration.lazy').then((d) => d.Route))

const AboutMeLazyRoute = AboutMeLazyImport.update({
  id: '/aboutMe',
  path: '/aboutMe',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/aboutMe.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/aboutMe': {
      id: '/aboutMe'
      path: '/aboutMe'
      fullPath: '/aboutMe'
      preLoaderRoute: typeof AboutMeLazyImport
      parentRoute: typeof rootRoute
    }
    '/illustration': {
      id: '/illustration'
      path: '/illustration'
      fullPath: '/illustration'
      preLoaderRoute: typeof IllustrationLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/aboutMe': typeof AboutMeLazyRoute
  '/illustration': typeof IllustrationLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/aboutMe': typeof AboutMeLazyRoute
  '/illustration': typeof IllustrationLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/aboutMe': typeof AboutMeLazyRoute
  '/illustration': typeof IllustrationLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aboutMe' | '/illustration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aboutMe' | '/illustration'
  id: '__root__' | '/' | '/aboutMe' | '/illustration'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutMeLazyRoute: typeof AboutMeLazyRoute
  IllustrationLazyRoute: typeof IllustrationLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutMeLazyRoute: AboutMeLazyRoute,
  IllustrationLazyRoute: IllustrationLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/aboutMe",
        "/illustration"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/aboutMe": {
      "filePath": "aboutMe.lazy.tsx"
    },
    "/illustration": {
      "filePath": "illustration.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
